[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "/en/latest/"
  to = "/introduction/"
  status = 301

[[redirects]]
  from = "/install/install-node.html"
  to = "/getting-started/installing-the-cardano-node/"
  status = 301

[[redirects]]
  from = "/install/use-cli.html"
  to = "/getting-started/use-cli/"
  status = 301

[[redirects]]
  from = "/getting-started/stake-pool-operators/index.html"
  to = "/getting-started/operating-a-stake-pool/about-stake-pools/"
  status = 301

[[redirects]]
  from = "/getting-started/guidelines-for-operating-large-stake-pools/index.html/"
  to = "/getting-started/guidelines-for-large-spos/"
  status = 301

[[redirects]]
  from = "/getting-started/3rd-party-integration/index.html/"
  to = "/getting-started/integrating-with-third-parties/"
  status = 301

[[redirects]]
  from = "/getting-started/exchanges/index.html"
  to = "/getting-started/running-stake-pools-and-delegation-for-exchanges/"
  status = 301

[[redirects]]
  from = "/explainers/cardano-explainers/what-is-a-blockchain.html"
  to = "/new-to-cardano/what-is-a-blockchain/"
  status = 301

[[redirects]]
  from = "/explainers/cardano-explainers/what-is-a-cryptocurrency.html"
  to = "/new-to-cardano/what-is-a-cryptocurrency"
  status = 301

[[redirects]]
  from = "/explainers/cardano-explainers/why-use-cardano.html"
  to = "/new-to-cardano/why-use-cardano/"
  status = 301

[[redirects]]
  from = "/explainers/cardano-explainers/proof-of-stake.html"
  to = "/new-to-cardano/proof-of-stake/"
  status = 301

[[redirects]]
  from = "/explainers/getting-started-with-cardano/cardano-nodes.html"
  to = "/new-to-cardano/cardano-nodes"
  status = 301

[[redirects]]
  from = "/explainers/getting-started-with-cardano/tools.html"
  to = "/new-to-cardano/cardano-tracking-tools/"
  status = 301

[[redirects]]
  from = "/explainers/getting-started-with-cardano/how-to-purchase-ada.html"
  to = "/new-to-cardano/how-to-purchase-ada/"
  status = 301

[[redirects]]
  from = "/explainers/cardano-explainers/types-of-wallets.html"
  to = "/new-to-cardano/types-of-wallets/"
  status = 301

[[redirects]]
  from = "/explainers/getting-started-with-cardano/how-to-delegate.html"
  to = "/new-to-cardano/how-to-delegate/"
  status = 301

[[redirects]]
  from = "/getting-started-with-cardano/how-to-delegate.html"
  to = "/new-to-cardano/how-to-delegate/"
  status = 301

[[redirects]]
  from = "/explainers/cardano-explainers/smart-contract-exp.html"
  to = "/new-to-cardano/what-is-a-smart-contract/"
  status = 301

[[redirects]]
  from = "/explore-cardano/what-is-a-cardano-node.html"
  to = "/core-concepts/cardano-node/"
  status = 301

[[redirects]]
  from = "/explore-cardano/what-is-a-stakepool.html"
  to = "/core-concepts/stake-pools/"
  status = 301

[[redirects]]
  from = "/explore-cardano/understanding-the-delegation-mechanism.html"
  to = "/core-concepts/delegation/"
  status = 301

[[redirects]]
  from = "/explore-cardano/understanding-pledging-and-rewards.html"
  to = "/core-concepts/pledging-rewards/"
  status = 301

[[redirects]]
  from = "/explore-cardano/understanding-pledging-and-rewards.html"
  to = "/core-concepts/pledging-rewards/"
  status = 301

[[redirects]]
  from = "/explore-cardano/understanding-pledging-and-rewards.html#distributing-rewards"
  to = "/pledging-rewards/#distributingrewards"
  status = 301

[[redirects]]
  from = "/learn/pledging-and-delegating-options.html"
  to = "/core-concepts/pledging-and-delegation-options/"
  status = 301

[[redirects]]
  from = "/explore-cardano/understanding-consensus.html"
  to = "/core-concepts/consensus-explained/"
  status = 301

[[redirects]]
  from = "/learn/Cardano-keys.html"
  to = "/core-concepts/cardano-keys/"
  status = 301

[[redirects]]
  from = "/learn/types-addresses.html"
  to = "/core-concepts/cardano-addresses/"
  status = 301

[[redirects]]
  from = "/explore-cardano/what-is-a-hard-fork-combinator.html"
  to = "/core-concepts/about-hard-forks/"
  status = 301

[[redirects]]
  from = "/learn/chain-confirmation-v-transaction-confirmation.html"
  to = "/core-concepts/chain-confirmation-versus-transaction-confirmation/"
  status = 301

[[redirects]]
  from = "/explore-cardano/design-rationale.html"
  to = "/explore-cardano/cardano-design-rationale/"
  status = 301

[[redirects]]
  from = "/explore-cardano/cardano-architecture-overview/index.html"
  to = "/explore-cardano/cardano-architecture/overview/"
  status = 301

[[redirects]]
  from = "/explore-cardano/cardano-network.html"
  to = "/explore-cardano/cardano-network/about-the-cardano-network/"
  status = 301

[[redirects]]
  from = "/explore-cardano/p2p-networking.html"
  to = "/explore-cardano/cardano-network/p2p-networking/"
  status = 301

[[redirects]]
  from = "/explore-cardano/cardano-monetary-policy.html"
  to = "/explore-cardano/monetary-policy/"
  status = 301

[[redirects]]
  from = "/explore-cardano/cardano-fee-structure.html"
  to = "/explore-cardano/fee-structure/"
  status = 301

[[redirects]]
  from = "/explore-cardano/further-reading.html"
  to = "/explore-cardano/resources/"
  status = 301

[[redirects]]
  from = "/explore-cardano/relevant-research-papers-and-specifications.html"
  to = "/explore-cardano/relevant-research-papers/"
  status = 301

[[redirects]]
  from = "/explorer.cardano.org/"
  to = "/tools/explorer/"
  status = 301

[[redirects]]
  from = "/projects/cardano-node/"
  to = "/cardano-components/cardano-node/"
  status = 301

[[redirects]]
  from = "/projects/smash/"
  to = "/cardano-components/smash/"
  status = 301

[[redirects]]
  from = "/rt-view/rt-view.html"
  to = "/cardano-components/cardano-rtview/"
  status = 301

[[redirects]]
  from = "/native-tokens/learn-about-native-tokens.html"
  to = "/native-tokens/learn/"
  status = 301

[[redirects]]
  from = "/native-tokens/minimum-ada-value-requirement.html"
  to = "/native-tokens/minimum-ada-value-requirement/"
  status = 301

[[redirects]]
  from = "/native-tokens/getting-started-with-native-tokens.html"
  to = "/native-tokens/getting-started/"
  status = 301

[[redirects]]
  from = "/native-tokens/exercises.html"
  to = "/native-tokens/exercises/"
  status = 301

[[redirects]]
  from = "/native-tokens/faqs.html"
  to = "/native-tokens/faqs/"
  status = 301

[[redirects]]
  from = "/marlowe/marlowe-explainer.html"
  to = "/marlowe/learn-about-marlowe/"
  status = 301

[[redirects]]
  from = "/marlowe/marlowe-get-started.html"
  to = "/marlowe/marlowe-get-started/"
  status = 301

[[redirects]]
  from = "/marlowe/marlowe-lang-guide.html"
  to = "/marlowe/marlowe-language-guide/"
  status = 301

[[redirects]]
  from = "/marlowe/get-started-blockly.html"
  to = "/marlowe/writing-marlowe-with-blockly/"
  status = 301

[[redirects]]
  from = "/marlowe/get-started-haskell.html"
  to = "/marlowe/using-the-haskell-editor/"
  status = 301

[[redirects]]
  from = "/marlowe/get-started-js.html"
  to = "/marlowe/using-javascript-editor/"
  status = 301

[[redirects]]
  from = "/rosetta/learn-Rosetta.html"
  to = "/rosetta/learn-rosetta/"
  status = 301

[[redirects]]
  from = "/rosetta/get-started-rosetta.html"
  to = "/rosetta/get-started-rosetta/"
  status = 301

[[redirects]]
  from = "/rosetta/contribute-rosetta.html"
  to = "/rosetta/contribute-rosetta/"
  status = 301

[[redirects]]
  from = "/release-information/comp-matrix.html"
  to = "/tools/comp-matrix/"
  status = 301

[[redirects]]
  from = "/cardano-community/cardano-improvement-proposals.html"
  to = "/community/cips/"
  status = 301

[[redirects]]
  from = "/cardano-community/providing-feedback.html"
  to = "/community/providing-feedback/"
  status = 301

[[redirects]]
  from = "/cardano-community/ambassadors-program.html"
  to = "/community/ambassador-program/"
  status = 301

[[redirects]]
  from = "/cardano-community/community-generated-content.html"
  to = "/community/community-content/"
  status = 301

[[redirects]]
  from = "/cardano-community/get-support.html"
  to = "/community/getting-support/"
  status = 301

[[redirects]]
  from = "/input-output-hk/bech32#bech32-command-line/"
  to = "/getting-started/use-cli/"
  status = 301

[[redirects]]
  from = "/input-output-hk/cardano-addresses#overview/"
  to = "https://github.com/input-output-hk/cardano-addresses#overview"
  status = 301

[[redirects]]
  from = "/latest/reference/cardano-node-cli-reference.html"
  to = "https://github.com/input-output-hk/cardano-node/blob/master/doc/reference/cardano-node-cli-reference.md"
  status = 301

[[redirects]]
  from = "/projects/cardano-serialization-lib/"
  to = "cardano-components/cardano-serialization-lib/"
  status = 301

[[redirects]]
  from = "/explore-cardano/glossary.html"
  to = "/glossary/"
  status = 301
  