import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'link',
      label: 'Cardano Ecosystem Tools',
      href: 'https://developers.cardano.org/tools/',
      className: 'cardano-ecosystems-external-link',
    },
    {
      type: 'link',
      label: 'Glossary',
      href: 'https://www.essentialcardano.io/glossary?sort=alphabetical',
      className: 'glossary-external-link',
    },
    {
      type: 'link',
      label: 'Cardano.org',
      href: 'https://cardano.org/',
      className: 'cardano-external-link',
    },
    {
      type: 'link',
      label: 'Developer Portal',
      href: 'https://developers.cardano.org/',
      className: 'cardano-developers-external-link',
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
}

export default sidebars
