import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  aboutCardano: [
    { type: 'autogenerated', dirName: 'about-cardano' },

    {
      type: 'link',
      label: 'Glossary',
      href: 'https://www.essentialcardano.io/glossary?sort=alphabetical',
      className: 'external-link-with-separator',
    },
    {
      type: 'link',
      label: 'FAQs',
      href: 'https://www.essentialcardano.io/faq',
    },
  ],
  developerResources: [
    { type: 'autogenerated', dirName: 'developer-resources' },
    {
      type: 'link',
      label: 'Weekly development reports',
      href: 'https://www.essentialcardano.io/development-update',
      className: 'external-link-with-separator',
    },
    {
      type: 'link',
      label: 'Builder tools',
      href: 'https://developers.cardano.org/tools',
    },
  ],
  stakePoolOperators: [
    { type: 'autogenerated', dirName: 'stake-pool-operators' },
  ],
  cardanoTestnets: [{ type: 'autogenerated', dirName: 'cardano-testnets' }],
  pioneerPrograms: [{ type: 'autogenerated', dirName: 'pioneer-programs' }],
}

export default sidebars
