/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Cardano Docs",
  "favicon": "img/cardano-favicon.png",
  "url": "https://docs.cardano.org",
  "baseUrl": "/",
  "organizationName": "IOHK",
  "projectName": "Cardano-documentation",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    [
      "@cmfcmf/docusaurus-search-local",
      {
        "indexDocs": true
      }
    ],
    [
      "docusaurus-node-polyfills",
      {
        "excludeAliases": [
          "console"
        ]
      }
    ],
    [
      "@docusaurus/plugin-client-redirects",
      {
        "redirects": [
          {
            "to": "/cardano-testnets/tools/faucet",
            "from": "/cardano-testnet/tools/faucet"
          },
          {
            "to": "/developer-resources/release-notes/comp-matrix",
            "from": "/tools/comp-matrix"
          },
          {
            "to": "/cardano-testnets/environments",
            "from": "/cardano-testnet/overview/"
          },
          {
            "to": "/cardano-testnets/environments",
            "from": "/cardano-testnet/about/testnet-introduction/"
          },
          {
            "to": "/cardano-testnets/getting-started",
            "from": "/cardano-testnet/getting-started/"
          },
          {
            "to": "/cardano-testnets/local-testnet",
            "from": "/cardano-testnet/local-testnet/"
          },
          {
            "to": "/cardano-testnets/resources",
            "from": "/cardano-testnet/resources/links/"
          },
          {
            "to": "/cardano-testnets/support-feedback",
            "from": "/cardano-testnet/support-feedback/"
          },
          {
            "to": "https://developers.cardano.org/docs/get-started/installing-cardano-node",
            "from": "/development-guidelines/installing-the-cardano-node/"
          },
          {
            "to": "https://cardano-course.gitbook.io/cardano-course/video-lessons",
            "from": "/development-guidelines/cardano-node-course"
          },
          {
            "to": "https://tests.cardano.intersectmbo.org/",
            "from": "/development-guidelines/node-tests/"
          },
          {
            "to": "https://github.com/IntersectMBO/cardano-cli?tab=readme-ov-file#overview-of-the-cardano-cli-repository",
            "from": "/development-guidelines/use-cli/"
          },
          {
            "to": "/developer-resources/welcome",
            "from": "/development-guidelines/transaction-tutorials/introduction/"
          },
          {
            "to": "https://github.com/IntersectMBO/cardano-node?tab=readme-ov-file#overview-of-the-cardano-node-repository",
            "from": "/cardano-components/cardano-node/"
          },
          {
            "to": "https://github.com/cardano-foundation/cardano-graphql#overview",
            "from": "/cardano-components/cardano-graphql/"
          },
          {
            "to": "https://github.com/cardano-foundation/cardano-rosetta?tab=readme-ov-file#cardano-rosetta",
            "from": "/cardano-components/cardano-rosetta/about-cardano-rosetta/"
          },
          {
            "to": "https://github.com/cardano-foundation/cardano-rosetta/tree/master/docs",
            "from": "/cardano-components/cardano-rosetta/learn/"
          },
          {
            "to": "https://github.com/cardano-foundation/cardano-rosetta/tree/master/docs",
            "from": "/cardano-components/cardano-rosetta/get-started-rosetta/"
          },
          {
            "to": "https://github.com/cardano-foundation/cardano-rosetta/tree/master/docs",
            "from": "/cardano-components/cardano-rosetta/api-calls-rosetta/"
          },
          {
            "to": "https://github.com/IntersectMBO/cardano-ledger#cardano-ledger",
            "from": "/cardano-components/cardano-ledger-specs/"
          },
          {
            "to": "https://github.com/IntersectMBO/cardano-db-sync#cardano-db-sync",
            "from": "/cardano-components/cardano-db-sync/about-db-sync/"
          },
          {
            "to": "https://github.com/IntersectMBO/cardano-db-sync?tab=readme-ov-file#architecture",
            "from": "/cardano-components/cardano-db-sync/db-sync-components/"
          },
          {
            "to": "https://github.com/IntersectMBO/cardano-db-sync?tab=readme-ov-file#installation",
            "from": "/cardano-components/cardano-db-sync/db-sync-set-up/"
          },
          {
            "to": "https://github.com/IntersectMBO/cardano-db-sync/tree/master/doc",
            "from": "/cardano-components/cardano-db-sync/best-practices/"
          },
          {
            "to": "https://github.com/input-output-hk/data-analytics-bigquery/wiki",
            "from": "/cardano-components/cardano-db-sync/big-query/"
          },
          {
            "to": "https://github.com/cardano-foundation/cardano-wallet#overview",
            "from": "/cardano-components/cardano-wallet/"
          },
          {
            "to": "https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/smash.md",
            "from": "/cardano-components/smash/"
          },
          {
            "to": "https://github.com/IntersectMBO/ouroboros-network#ouroboros-network",
            "from": "/cardano-components/ouroboros-network/"
          },
          {
            "to": "https://github.com/IntersectMBO/cardano-node/blob/master/cardano-tracer/docs/cardano-rtview.md",
            "from": "/cardano-components/cardano-rtview/"
          },
          {
            "to": "https://github.com/Emurgo/cardano-serialization-lib?tab=readme-ov-file#cardano-serialization-lib",
            "from": "/cardano-components/cardano-serialization-lib/"
          },
          {
            "to": "https://github.com/input-output-hk/daedalus",
            "from": "/cardano-components/daedalus-wallet/"
          },
          {
            "to": "https://beta.explorer.cardano.org/en/",
            "from": "/cardano-components/cardano-explorer/"
          },
          {
            "to": "https://github.com/input-output-hk/sc-evm/blob/main/TECHNICAL_SPECIFICATION_v1.1.pdf",
            "from": "/cardano-sidechains/basics/introduction-sidechains/"
          },
          {
            "to": "https://github.com/input-output-hk/sc-evm/blob/main/TECHNICAL_SPECIFICATION_v1.1.pdf",
            "from": "/cardano-sidechains/basics/ouroboros-description/"
          },
          {
            "to": "https://github.com/input-output-hk/sc-evm/blob/main/TECHNICAL_SPECIFICATION_v1.1.pdf",
            "from": "/cardano-sidechains/basics/block-explorer/"
          },
          {
            "to": "https://github.com/input-output-hk/sc-evm/blob/main/TECHNICAL_SPECIFICATION_v1.1.pdf",
            "from": "/cardano-sidechains/sidechain-toolkit/introduction/"
          },
          {
            "to": "https://github.com/input-output-hk/sc-evm/blob/main/TECHNICAL_SPECIFICATION_v1.1.pdf",
            "from": "/cardano-sidechains/sidechain-toolkit/mainchain-plutus-scripts/"
          },
          {
            "to": "https://github.com/input-output-hk/sc-evm/blob/main/TECHNICAL_SPECIFICATION_v1.1.pdf",
            "from": "/cardano-sidechains/sidechain-toolkit/chain-follower/"
          },
          {
            "to": "https://github.com/input-output-hk/sc-evm/blob/main/TECHNICAL_SPECIFICATION_v1.1.pdf",
            "from": "/cardano-sidechains/sidechain-toolkit/committee-rotation/"
          },
          {
            "to": "https://github.com/input-output-hk/sc-evm/blob/main/TECHNICAL_SPECIFICATION_v1.1.pdf",
            "from": "/cardano-sidechains/proof-of-concept-evm-sidechain/create-and-fund-accounts/"
          },
          {
            "to": "https://github.com/input-output-hk/sc-evm/blob/main/TECHNICAL_SPECIFICATION_v1.1.pdf",
            "from": "/cardano-sidechains/proof-of-concept-evm-sidechain/metamask/"
          },
          {
            "to": "https://github.com/input-output-hk/sc-evm/blob/main/TECHNICAL_SPECIFICATION_v1.1.pdf",
            "from": "/cardano-sidechains/proof-of-concept-evm-sidechain/deploy-smart-contracts/setup-development/"
          },
          {
            "to": "https://github.com/input-output-hk/sc-evm/blob/main/TECHNICAL_SPECIFICATION_v1.1.pdf",
            "from": "/cardano-sidechains/proof-of-concept-evm-sidechain/deploy-smart-contracts/verify-contract/"
          },
          {
            "to": "https://github.com/input-output-hk/sc-evm/blob/main/TECHNICAL_SPECIFICATION_v1.1.pdf",
            "from": "/cardano-sidechains/proof-of-concept-evm-sidechain/deploy-smart-contracts/solidity-resources/"
          },
          {
            "to": "https://github.com/input-output-hk/sc-evm/blob/main/TECHNICAL_SPECIFICATION_v1.1.pdf",
            "from": "/cardano-sidechains/proof-of-concept-evm-sidechain/sidechain-token/"
          },
          {
            "to": "https://github.com/input-output-hk/sc-evm/blob/main/TECHNICAL_SPECIFICATION_v1.1.pdf",
            "from": "/cardano-sidechains/proof-of-concept-evm-sidechain/transferring-tokens/"
          },
          {
            "to": "/developer-resources/native-tokens",
            "from": "/native-tokens/learn/"
          },
          {
            "to": "https://cardano-ledger.readthedocs.io/en/latest/explanations/min-utxo-mary.html",
            "from": "/native-tokens/minimum-ada-value-requirement/"
          },
          {
            "to": "https://developers.cardano.org/docs/native-tokens/minting",
            "from": "/native-tokens/getting-started/"
          },
          {
            "to": "https://github.com/input-output-hk/cardano-node-wiki/blob/main/docs/reference/native-tokens/03-exercises.md",
            "from": "/native-tokens/exercises/"
          },
          {
            "to": "https://cardano-ledger.readthedocs.io/en/latest/explanations/faq.html",
            "from": "/native-tokens/faqs/"
          },
          {
            "to": "https://github.com/input-output-hk/cardano-node-wiki/blob/main/docs/reference/native-tokens/04-exchange-scenarios.md",
            "from": "/exchange-multi-asset-management-scenarios/"
          },
          {
            "to": "https://cardano-ledger.readthedocs.io/en/latest/explanations/listing.html",
            "from": "/listing-cardano-native-assets-on-an-exchange/"
          },
          {
            "to": "https://plutus.readthedocs.io/en/latest/simple-example.html",
            "from": "/smart-contracts/plutus/plutus-scripts/"
          },
          {
            "to": "https://plutus.readthedocs.io/en/latest/index.html",
            "from": "/smart-contracts/plutus/dapp-development/"
          },
          {
            "to": "https://plutus.readthedocs.io/en/latest/index.html",
            "from": "/smart-contracts/plutus/plutus-use-cases/"
          },
          {
            "to": "/about-cardano/learn/collateral-mechanism",
            "from": "/smart-contracts/plutus/collateral-mechanism/"
          },
          {
            "to": "/about-cardano/learn/transaction-costs-determinism",
            "from": "/smart-contracts/plutus/transaction-costs-determinism/"
          },
          {
            "to": "/developer-resources/smart-contracts/plutus",
            "from": "/smart-contracts/plutus/sc-best-practices/"
          },
          {
            "to": "/developer-resources/smart-contracts/marlowe",
            "from": "/smart-contracts/marlowe/learn-about-marlowe/"
          },
          {
            "to": "/developer-resources/smart-contracts/aiken",
            "from": "/smart-contracts/aiken/learn-about-aiken/"
          },
          {
            "to": "https://cips.cardano.org/",
            "from": "/community/cips"
          },
          {
            "to": "https://www.essentialcardano.io/",
            "from": "/community/essential-cardano"
          },
          {
            "to": "https://cardano.org/ambassadors/",
            "from": "/community/ambassador-program"
          },
          {
            "to": "https://iohk.zendesk.com/hc/en-us",
            "from": "/community/getting-support"
          },
          {
            "to": "/about-cardano/introduction",
            "from": "/introduction/"
          },
          {
            "to": "/about-cardano/new-to-cardano/",
            "from": "/new-to-cardano/introduction/"
          },
          {
            "to": "/about-cardano/new-to-cardano/what-is-a-blockchain",
            "from": "/new-to-cardano/what-is-a-blockchain/"
          },
          {
            "to": "/about-cardano/new-to-cardano/what-is-a-cryptocurrency",
            "from": "/new-to-cardano/what-is-a-cryptocurrency/"
          },
          {
            "to": "/about-cardano/evolution/cardano-design-rationale#cardano-advantages",
            "from": "/new-to-cardano/why-use-cardano/"
          },
          {
            "to": "/about-cardano/new-to-cardano/proof-of-stake",
            "from": "/new-to-cardano/proof-of-stake/"
          },
          {
            "to": "/about-cardano/new-to-cardano/cardano-tracking-tools",
            "from": "/new-to-cardano/cardano-tracking-tools/"
          },
          {
            "to": "/about-cardano/new-to-cardano/types-of-wallets#where-to-store-ada",
            "from": "/new-to-cardano/how-to-purchase-ada/"
          },
          {
            "to": "/about-cardano/new-to-cardano/types-of-wallets",
            "from": "/new-to-cardano/types-of-wallets/"
          },
          {
            "to": "/about-cardano/new-to-cardano/how-to-delegate",
            "from": "/new-to-cardano/how-to-delegate/"
          },
          {
            "to": "/about-cardano/new-to-cardano/what-is-a-smart-contract",
            "from": "/new-to-cardano/what-is-a-smart-contract/"
          },
          {
            "to": "/about-cardano/learn/cardano-node",
            "from": "/learn/cardano-node/"
          },
          {
            "to": "/about-cardano/learn/stake-pools",
            "from": "/learn/stake-pools/"
          },
          {
            "to": "/about-cardano/learn/delegation",
            "from": "/learn/delegation/"
          },
          {
            "to": "/about-cardano/learn/pledging-rewards",
            "from": "/learn/pledging-rewards/"
          },
          {
            "to": "/about-cardano/learn/pledging-rewards",
            "from": "/learn/pledging-and-delegation-options/"
          },
          {
            "to": "/about-cardano/learn/consensus-explained",
            "from": "/learn/consensus-explained/"
          },
          {
            "to": "/about-cardano/learn/ouroboros-overview",
            "from": "/learn/ouroboros-overview/"
          },
          {
            "to": "/about-cardano/learn/cardano-keys",
            "from": "/learn/cardano-keys/"
          },
          {
            "to": "/about-cardano/learn/cardano-addresses",
            "from": "/learn/cardano-addresses/"
          },
          {
            "to": "/about-cardano/evolution/about-hard-forks",
            "from": "/learn/about-hard-forks/"
          },
          {
            "to": "/about-cardano/learn/chain-confirmation-versus-transaction-confirmation",
            "from": "/learn/chain-confirmation-versus-transaction-confirmation/"
          },
          {
            "to": "/about-cardano/learn/eutxo-explainer",
            "from": "/learn/eutxo-explainer/"
          },
          {
            "to": "/about-cardano/evolution/cardano-design-rationale",
            "from": "/explore-cardano/cardano-design-rationale/"
          },
          {
            "to": "/about-cardano/evolution/eras-and-phases",
            "from": "/explore-cardano/eras-and-phases/"
          },
          {
            "to": "/about-cardano/explore-more/cardano-architecture",
            "from": "/explore-cardano/cardano-architecture/"
          },
          {
            "to": "/about-cardano/explore-more/cardano-network/",
            "from": "/explore-cardano/cardano-network/about-the-cardano-network/"
          },
          {
            "to": "/about-cardano/explore-more/cardano-network/networking-protocol",
            "from": "/explore-cardano/cardano-network/networking-protocol/"
          },
          {
            "to": "/about-cardano/explore-more/cardano-network/p2p-networking",
            "from": "/explore-cardano/cardano-network/p2p-networking/"
          },
          {
            "to": "/about-cardano/introduction",
            "from": "/explore-cardano/cardano-entropy/"
          },
          {
            "to": "/about-cardano/explore-more/fee-structure",
            "from": "/explore-cardano/fee-structure/"
          },
          {
            "to": "/about-cardano/explore-more/monetary-policy",
            "from": "/explore-cardano/monetary-policy/"
          },
          {
            "to": "/about-cardano/introduction",
            "from": "/explore-cardano/explain-nonce/"
          },
          {
            "to": "/about-cardano/explore-more/time",
            "from": "/explore-cardano/time/"
          },
          {
            "to": "/about-cardano/explore-more/concurrency",
            "from": "/explore-cardano/concurrency/"
          },
          {
            "to": "/about-cardano/explore-more/relevant-research-papers",
            "from": "/explore-cardano/relevant-research-papers/"
          },
          {
            "to": "/about-cardano/explore-more/parameter-guide",
            "from": "/explore-cardano/parameter-guide/"
          },
          {
            "to": "/about-cardano/evolution/upgrades/vasil",
            "from": "/cardano-testnet/about/feature-overview/"
          },
          {
            "to": "/about-cardano/evolution/upgrades/valentine",
            "from": "/cardano-testnet/about/secp/"
          },
          {
            "to": "/cardano-testnets/tools/daedalus-testnet",
            "from": "/cardano-testnet/daedalus-testnet/"
          },
          {
            "to": "/about-cardano/new-to-cardano/staking-calculator",
            "from": "/cardano-testnet/tools/staking-calculator/"
          },
          {
            "to": "/cardano-testnets/tools/plutus-fee-estimator",
            "from": "/cardano-testnet/tools/plutus-fee-estimator/"
          },
          {
            "to": "/stake-pool-operators/monitoring",
            "from": "/development-guidelines/node-monitoring/"
          },
          {
            "to": "/stake-pool-operators/operating-a-stake-pool",
            "from": "/operating-a-stake-pool/stake-pool-operations-101/"
          },
          {
            "to": "/stake-pool-operators/about-stake-pools",
            "from": "/operating-a-stake-pool/about-stake-pools/"
          },
          {
            "to": "/stake-pool-operators/operating-a-stake-pool",
            "from": "/operating-a-stake-pool/creating-a-stake-pool/"
          },
          {
            "to": "/stake-pool-operators/node-connectivity",
            "from": "/operating-a-stake-pool/node-connectivity/"
          },
          {
            "to": "/stake-pool-operators/creating-keys-and-certificates",
            "from": "/operating-a-stake-pool/creating-keys-and-certificates/"
          },
          {
            "to": "/stake-pool-operators/maintenance",
            "from": "/operating-a-stake-pool/public-stake-pools/"
          },
          {
            "to": "/stake-pool-operators/metadata-management",
            "from": "/operating-a-stake-pool/smash/"
          },
          {
            "to": "/stake-pool-operators/performance",
            "from": "/operating-a-stake-pool/performance/"
          },
          {
            "to": "/stake-pool-operators/ranking",
            "from": "/operating-a-stake-pool/ranking/"
          },
          {
            "to": "/stake-pool-operators/guidelines-for-large-spos",
            "from": "/operating-a-stake-pool/guidelines-for-large-spos/"
          },
          {
            "to": "https://github.com/input-output-hk/cardano-node-wiki/blob/main/docs/reference/native-tokens/04-exchange-scenarios.md",
            "from": "/native-tokens/exchange-multi-asset-management-scenarios/"
          },
          {
            "to": "https://cardano-ledger.readthedocs.io/en/latest/explanations/listing.html",
            "from": "/native-tokens/listing-cardano-native-assets-on-an-exchange/"
          },
          {
            "to": "/developer-resources/smart-contracts/plutus",
            "from": "/smart-contracts/plutus/learn-about-plutus/"
          },
          {
            "to": "/developer-resources/smart-contracts/plutus",
            "from": "/smart-contracts/plutus/plutus-resources/"
          },
          {
            "to": "/developer-resources/release-notes/release-notes",
            "from": "/tools/release-notes/"
          }
        ]
      }
    ]
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "editUrl": "https://github.com/input-output-hk/cardano-documentation/blob/master/",
          "editLocalizedFiles": true,
          "sidebarPath": "./sidebars.ts",
          "routeBasePath": "/"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/cardano-logo.svg",
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": true,
      "respectPrefersColorScheme": true
    },
    "navbar": {
      "logo": {
        "alt": "Cardano logo",
        "src": "img/cardano-logo.svg"
      },
      "items": [
        {
          "to": "about-cardano/introduction",
          "label": "About Cardano",
          "position": "left"
        },
        {
          "to": "developer-resources/welcome",
          "label": "Developer resources",
          "position": "left"
        },
        {
          "to": "stake-pool-operators/operating-a-stake-pool",
          "label": "Stake pool operations",
          "position": "left"
        },
        {
          "to": "cardano-testnets/environments",
          "label": "Cardano testnets",
          "position": "left"
        },
        {
          "to": "pioneer-programs/plutus-pioneers",
          "label": "Pioneer programs",
          "position": "left"
        },
        {
          "type": "dropdown",
          "label": "Community",
          "position": "left",
          "items": [
            {
              "label": "Support",
              "href": "https://iohk.zendesk.com/hc/en-us/requests/new"
            },
            {
              "label": "Essential Cardano",
              "href": "https://www.essentialcardano.io/"
            },
            {
              "label": "Cardano Stack Exchange",
              "href": "https://cardano.stackexchange.com/"
            },
            {
              "label": "Ambassadors program",
              "href": "https://cardano.org/ambassadors/"
            },
            {
              "label": "Cardano Improvement Proposals (CIPs)",
              "href": "https://cips.cardano.org/"
            }
          ]
        },
        {
          "label": "Developer portal",
          "href": "https://developers.cardano.org/",
          "position": "left"
        },
        {
          "label": "GitHub",
          "href": "https://github.com/input-output-hk/cardano-documentation",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "logo": {
        "alt": "Cardano Logo",
        "src": "img/cardano-logo.svg"
      },
      "links": [
        {
          "title": "More About Cardano",
          "items": [
            {
              "label": "Cardano Explorer",
              "href": "https://cardanoexplorer.com/"
            },
            {
              "label": "Cardano Foundation",
              "href": "https://cardanofoundation.org/"
            },
            {
              "label": "Cardano.org",
              "href": "https://www.cardano.org/"
            },
            {
              "label": "Why Cardano",
              "href": "https://why.cardano.org/"
            },
            {
              "label": "Daedalus",
              "href": "https://daedaluswallet.io/"
            }
          ]
        },
        {
          "title": "Join the community",
          "items": [
            {
              "label": "Cardano Community",
              "href": "https://cardano.org/"
            },
            {
              "label": "Cardano Telegram",
              "href": "https://t.me/CardanoAnnouncements/"
            },
            {
              "label": "Cardano Forum",
              "href": "https://forum.cardano.org/"
            },
            {
              "label": "Cardano Reddit",
              "href": "https://www.reddit.com/r/cardano/"
            },
            {
              "label": "IOHK",
              "href": "https://www.iohk.io/"
            },
            {
              "label": "IOHK blog",
              "href": "https://www.iohk.io/blog/"
            },
            {
              "label": "IOHK YouTube",
              "href": "https://www.youtube.com/channel/UCBJ0p9aCW-W82TwNM-z3V2w"
            },
            {
              "label": "Cardano Foundation YouTube",
              "href": "https://www.youtube.com/channel/UCbQ9vGfezru1YRI1zDCtTGg"
            },
            {
              "label": "Cardano Foundation Twitter",
              "href": "https://twitter.com/Cardano_CF"
            },
            {
              "label": "IOG Academy",
              "href": "https://www.youtube.com/channel/UCX9j__vYOJu00iqBrCzecVw"
            }
          ]
        },
        {
          "title": "Legal",
          "items": [
            {
              "label": "IOHK Privacy Policy",
              "href": "https://static.iohk.io/terms/iog-privacy-policy.pdf"
            },
            {
              "label": "IOHK Terms & Conditions",
              "href": "https://static.iohk.io/terms/iohktermsandconditions.pdf"
            }
          ]
        },
        {
          "title": "Social",
          "items": [
            {
              "label": "X",
              "href": "https://twitter.com/inputoutputHK"
            },
            {
              "label": "Facebook",
              "href": "https://www.facebook.com/iohk.io/"
            },
            {
              "label": "Youtube",
              "href": "https://www.youtube.com/c/IohkIo"
            },
            {
              "label": "Blog",
              "href": "https://iohk.io/en/blog/posts/page-1/"
            }
          ]
        }
      ],
      "copyright": "Cardano is an open-source project. \n      \n      Cardano is a software platform ONLY and does not conduct any independent diligence on, or substantive review of, any blockchain asset, digital currency, cryptocurrency or associated funds. You are fully and solely responsible for evaluating your investments, for determining whether you will exchange blockchain assets based on your own judgement, and for all your decisions as to whether to exchange blockchain assets with Cardano. In many cases, blockchain assets you exchange on the basis of your research may not increase in value, and may decrease in value. Similarly, blockchain assets you exchange on the basis of your research may fall or rise in value after your exchange.\n      \n      Past performance is not indicative of future results. Any investment in blockchain assets involves the risk of loss of part or all of your investment. The value of the blockchain assets you exchange is subject to market and other investment risks.\n      \n      © IOHK 2015-2024 - IOHK Supported Project"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "tagline": "",
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
