/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Cardano Docs",
  "favicon": "img/cardano-favicon.png",
  "url": "https://docs.cardano.org",
  "baseUrl": "/",
  "organizationName": "IOHK",
  "projectName": "Cardano-documentation",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    [
      "docusaurus-node-polyfills",
      {
        "excludeAliases": [
          "console"
        ]
      }
    ],
    [
      "@docusaurus/plugin-client-redirects",
      {
        "redirects": [
          {
            "to": "/cardano-testnets/tools/faucet",
            "from": "/cardano-testnet/tools/faucet"
          },
          {
            "to": "/release-notes/comp-matrix",
            "from": "/tools/comp-matrix"
          }
        ]
      }
    ]
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "routeBasePath": "/",
          "editUrl": "https://github.com/input-output-hk/cardano-documentation/blob/master/"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/cardano-logo.svg",
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": true,
      "respectPrefersColorScheme": true
    },
    "navbar": {
      "logo": {
        "alt": "Cardano logo",
        "src": "img/cardano-logo.svg"
      },
      "items": [
        {
          "href": "https://github.com/input-output-hk/cardano-documentation",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "logo": {
        "alt": "Cardano Logo",
        "src": "img/cardano-logo.svg"
      },
      "links": [
        {
          "title": "More About Cardano",
          "items": [
            {
              "label": "Cardano Explorer",
              "href": "https://cardanoexplorer.com/"
            },
            {
              "label": "Cardano Foundation",
              "href": "https://cardanofoundation.org/"
            },
            {
              "label": "Cardano.org",
              "href": "https://www.cardano.org/"
            },
            {
              "label": "Why Cardano",
              "href": "https://why.cardano.org/"
            },
            {
              "label": "Daedalus",
              "href": "https://daedaluswallet.io/"
            }
          ]
        },
        {
          "title": "Join the community",
          "items": [
            {
              "label": "Cardano Community",
              "href": "https://cardano.org/"
            },
            {
              "label": "Cardano Telegram",
              "href": "https://t.me/CardanoAnnouncements/"
            },
            {
              "label": "Cardano Forum",
              "href": "https://forum.cardano.org/"
            },
            {
              "label": "Cardano Reddit",
              "href": "https://www.reddit.com/r/cardano/"
            },
            {
              "label": "IOHK",
              "href": "https://www.iohk.io/"
            },
            {
              "label": "IOHK blog",
              "href": "https://www.iohk.io/blog/"
            },
            {
              "label": "IOHK YouTube",
              "href": "https://www.youtube.com/channel/UCBJ0p9aCW-W82TwNM-z3V2w"
            },
            {
              "label": "Cardano Foundation YouTube",
              "href": "https://www.youtube.com/channel/UCbQ9vGfezru1YRI1zDCtTGg"
            },
            {
              "label": "Cardano Foundation Twitter",
              "href": "https://twitter.com/Cardano_CF"
            },
            {
              "label": "IOG Academy",
              "href": "https://www.youtube.com/channel/UCX9j__vYOJu00iqBrCzecVw"
            }
          ]
        },
        {
          "title": "Legal",
          "items": [
            {
              "label": "IOHK Privacy Policy",
              "href": "https://static.iohk.io/terms/iog-privacy-policy.pdf"
            },
            {
              "label": "IOHK Terms & Conditions",
              "href": "https://static.iohk.io/terms/iohktermsandconditions.pdf"
            }
          ]
        },
        {
          "title": "Social",
          "items": [
            {
              "label": "X",
              "href": "https://twitter.com/inputoutputHK"
            },
            {
              "label": "Facebook",
              "href": "https://www.facebook.com/iohk.io/"
            },
            {
              "label": "Youtube",
              "href": "https://www.youtube.com/c/IohkIo"
            },
            {
              "label": "Blog",
              "href": "https://iohk.io/en/blog/posts/page-1/"
            }
          ]
        }
      ],
      "copyright": "Cardano is an open-source project. \n      \n      Cardano is a software platform ONLY and does not conduct any independent diligence on, or substantive review of, any blockchain asset, digital currency, cryptocurrency or associated funds. You are fully and solely responsible for evaluating your investments, for determining whether you will exchange blockchain assets based on your own judgement, and for all your decisions as to whether to exchange blockchain assets with Cardano. In many cases, blockchain assets you exchange on the basis of your research may not increase in value, and may decrease in value. Similarly, blockchain assets you exchange on the basis of your research may fall or rise in value after your exchange.\n      \n      Past performance is not indicative of future results. Any investment in blockchain assets involves the risk of loss of part or all of your investment. The value of the blockchain assets you exchange is subject to market and other investment risks.\n      \n      © IOHK 2015-2024 - IOHK Supported Project"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "tagline": "",
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
